Ported batchelor to SUN Solaris 8.

diff --git a/utils/script.sh.in b/utils/script.sh.in
--- a/utils/script.sh.in
+++ b/utils/script.sh.in
@@ -33,6 +33,12 @@
 # The states in (1) is out of control of this script, it only depends on batch 
 # queue properties. The states in (2) is direct affected by this script. Use the 
 # qsignal($state, $msg) function to communicate state to batchelor.
+#
+# NOTES:
+# 1. Solaris 8 (and later?)
+#    a) You need to compile date.c because the system date don't support -u '%s'
+#    b) Change first line in this script from /bin/sh to /usr/bin/bash becaue
+#       /bin/sh don't understand function xxx() syntax.
 
 ##
 ## Required parameters:
@@ -40,7 +46,7 @@
 jobdir="$1"
 indata="$2"
 resdir="$3"
-
+      
 ##
 ## Use this function to communicate the state to batchelor.
 ##
@@ -70,9 +76,16 @@ function qsignal()
 }
 
 ##
-## Signal started to batchelor:
+## Make sure we got a date command that supports -u '%s' in PATH. For Solaris 8
+## (and later?) the utils/date.c can be compiled and used.
 ##
-qsignal "started"
+if [ "`uname -s`" == "SunOS" ]; then
+  if ! [ -e $(dirname $0)/date ]; then
+    qsignal "fatal" "Sun OS detected but date replacement is missing"
+  else
+    export PATH=$(dirname $0):$PATH
+  fi
+fi
 
 ##
 ## Sanity check:
@@ -80,10 +93,15 @@ qsignal "started"
 [ -z "$jobdir" -o -z "$indata" -o -z "$resdir" ] && qsignal "fatal" "missing argument for script"
 
 ##
+## Signal started to batchelor:
+##
+qsignal "started"
+
+##
 ## Put the command to run here with stdout and stderr redirected.
 ## The command must be in PATH or being an absolute path.
 ##
-$(dirname $0)/simula -i $indata -r $resdir 1> $jobdir/stdout 2> $jobdir/stderr
+$(dirname $0)/simula -s warning -i $indata -r $resdir 1> $jobdir/stdout 2> $jobdir/stderr
 
 ##
 ## Signal finished to batchelor:
